### ISSUE TITLE
Cannot use js

### ISSUE THREAD

**Issue by alanshaw** [alanshaw/iim#33]
```console
$ iim use js
✖ failed to find js-ipfs versions
file:///opt/homebrew/lib/node_modules/iim/dist/src/lib/npm/index.js:40
            throw new Error(`${mod} has no versions to select from`);
                  ^

Error: ipfs has no versions to select from
    at NpmLib.rangeToVersion (file:///opt/homebrew/lib/node_modules/iim/dist/src/lib/npm/index.js:40:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async selectVersion (file:///opt/homebrew/lib/node_modules/iim/dist/src/lib/use/select-version.js:7:19)
    at async use (file:///opt/homebrew/lib/node_modules/iim/dist/src/lib/use/index.js:21:21)
    at async Object.run (file:///opt/homebrew/lib/node_modules/iim/dist/src/commands/use.js:37:9)
    at async file:///opt/homebrew/lib/node_modules/iim/dist/src/bin.js:14:1

Node.js v20.9.0
```

**Comment by achingbrain** [comment]
This is a bit of an edge case as all js-ipfs versions have been deprecated so they were being excluded from the list of versions to install from.

The tedious reason the deprecated check became necessary was that kubo took over the name of an older unused module which already had a (now deprecated) v1 published.

#36 improves the error message and also allows passing a `--deprecated` flag similar to `iim list`.
